### ISSUE TITLE
Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by darionyaphet** [klugjo/hexo-theme-phantom#2]
Hi  

I try to use `hexo-theme-phantom`  in my blog  

I checkout git repo and meet a small question  as following : 

```
ERROR Process failed: source/sass/layout/_wrapper.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/theme/index.js:71:20)
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:628:18)
    at Promise._resolveCallback (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:423:57)
    at Promise._settlePromiseFromHandler (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:514:17)
    at Promise._settlePromise (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/promise.js:628:18)
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/darion.johannes.yaphet/darionyaphet.github.io/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Is there something miss or should I install something ?  thank you :）

**Comment by klugjo** [comment]
Hi @darionyaphet 

Actually there seems to be a bug in Hexo's latest version (3.2.0)

https://github.com/hexojs/hexo/issues/1793

Can you try to downgrade to version 3.1.1 and see if it solves the problem. Once the hexo team has fixed the problem, you will be able to use the latest version again.

I have noticed a few themes are having this issues as well.

https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/224

Hope that helps

**Comment by klugjo** [comment]
Also just in case you have not done so, do not forget to install the scss renderer:

```
npm install --save hexo-renderer-scss
```

**Comment by darionyaphet** [comment]
@klugjo running is ok and fixed this error :)   But it seems some resource not found

**Comment by klugjo** [comment]
@darionyaphet Can you give me more details on what ressources are not found ?

Thanks

**Comment by darionyaphet** [comment]
@klugjo  I can't upload picture to github  ..><.. 

Could I send a e-mail to you ?

**Comment by darionyaphet** [comment]
@klugjo I upload a picture at [here](https://i.imgsafe.org/e023373.png)

**Comment by klugjo** [comment]
I have just made some changes that might help. 

If I follow these steps, it works for me:
1. `mkdir blog`
2. `cd blog`
3. `hexo init`
4. `npm install`
5. `npm install --save hexo-renderer-scss`
6. `git clone https://github.com/klugjo/hexo-theme-phantom themes/phantom`
7. Go to _config.yml and change the theme to `phantom`
8. `hexo generate`
9. `hexo server`

Working.

Let me know if that is ok with you

**Comment by darionyaphet** [comment]
It seems don't work . Maybe something mistake . thank you for you help :)
